import {
  Aria2AddMetalinkCall,
  Aria2AddMetalinkResult,
  Aria2AddTorrentCall,
  Aria2AddTorrentResult,
  Aria2AddUriCall,
  Aria2AddUriResult,
  Aria2ChangePositionCall,
  Aria2ChangePositionResult,
  Aria2ChangeUriCall,
  Aria2ChangeUriResult,
  Aria2ForcePauseAllCall,
  Aria2ForcePauseAllResult,
  Aria2ForcePauseCall,
  Aria2ForcePauseResult,
  Aria2ForceRemoveCall,
  Aria2ForceRemoveResult,
  Aria2GetFilesCall,
  Aria2GetFilesResult,
  Aria2GetPeersCall,
  Aria2GetPeersResult,
  Aria2GetServersCall,
  Aria2GetServersResult,
  Aria2GetUrisCall,
  Aria2GetUrisResult,
  Aria2PauseAllCall,
  Aria2PauseAllResult,
  Aria2PauseCall,
  Aria2PauseResult,
  Aria2PurgeDownloadResultCall,
  Aria2PurgeDownloadResultResult,
  Aria2RemoveCall,
  Aria2RemoveDownloadResultCall,
  Aria2RemoveDownloadResultResult,
  Aria2RemoveResult,
  Aria2TellActiveCall,
  Aria2TellActiveResult,
  Aria2TellStatusCall,
  Aria2TellStatusResult,
  Aria2TellStoppedCall,
  Aria2TellStoppedResult,
  Aria2TellWaitingCall,
  Aria2TellWaitingResult,
  Aria2UnpauseAllCall,
  Aria2UnpauseAllResult,
  Aria2UnpauseCall,
  Aria2UnpauseResult,
} from './download'

import type {
  Aria2ChangeGlobalOptionCall,
  Aria2ChangeGlobalOptionResult,
  Aria2ChangeOptionCall,
  Aria2ChangeOptionResult,
  Aria2GetGlobalOptionCall,
  Aria2GetGlobalOptionResult,
  Aria2GetOptionCall,
  Aria2GetOptionResult,
} from './option'

import type {
  Aria2ForceShutdownCall,
  Aria2ForceShutdownResult,
  Aria2GetGlobalStatCall,
  Aria2GetGlobalStatResult,
  Aria2GetSessionInfoCall,
  Aria2GetSessionInfoResult,
  Aria2GetVersionCall,
  Aria2GetVersionResult,
  Aria2SaveSessionCall,
  Aria2SaveSessionResult,
  Aria2ShutdownCall,
  Aria2ShutdownResult,
} from './server'

import type {
  Aria2SystemListMethodsCall,
  Aria2SystemListMethodsResult,
  Aria2SystemListNotificationsCall,
  Aria2SystemListNotificationsResult,
  Aria2SystemMulticallCall,
  Aria2SystemMulticallResult,
} from './system'
import type {
  Aria2RpcMethod,
  Aria2RpcMethodCallMap,
  Aria2RpcMethodResultMap,
} from './method'
import type { Aria2ClientNotificationCall } from './notification'
import type {
  Aria2StringUtf8,
  Aria2ServerOpResult,
  Aria2ClientGidOpParams,
  Aria2ClientGidOpCall,
  Aria2ServerVoidCall,
} from './utils'
declare module 'maria2' {
  export type {
    Aria2RpcMethod,
    Aria2RpcMethodCallMap,
    Aria2RpcMethodResultMap,
    Aria2AddMetalinkCall,
    Aria2AddMetalinkResult,
    Aria2AddTorrentCall,
    Aria2AddTorrentResult,
    Aria2AddUriCall,
    Aria2AddUriResult,
    Aria2ChangePositionCall,
    Aria2ChangePositionResult,
    Aria2ChangeUriCall,
    Aria2ChangeUriResult,
    Aria2ForcePauseAllCall,
    Aria2ForcePauseAllResult,
    Aria2ForcePauseCall,
    Aria2ForcePauseResult,
    Aria2ForceRemoveCall,
    Aria2ForceRemoveResult,
    Aria2GetFilesCall,
    Aria2GetFilesResult,
    Aria2GetPeersCall,
    Aria2GetPeersResult,
    Aria2GetServersCall,
    Aria2GetServersResult,
    Aria2GetUrisCall,
    Aria2GetUrisResult,
    Aria2PauseAllCall,
    Aria2PauseAllResult,
    Aria2PauseCall,
    Aria2PauseResult,
    Aria2PurgeDownloadResultCall,
    Aria2PurgeDownloadResultResult,
    Aria2RemoveCall,
    Aria2RemoveDownloadResultCall,
    Aria2RemoveDownloadResultResult,
    Aria2RemoveResult,
    Aria2TellActiveCall,
    Aria2TellActiveResult,
    Aria2TellStatusCall,
    Aria2TellStatusResult,
    Aria2TellStoppedCall,
    Aria2TellStoppedResult,
    Aria2TellWaitingCall,
    Aria2TellWaitingResult,
    Aria2UnpauseAllCall,
    Aria2UnpauseAllResult,
    Aria2UnpauseCall,
    Aria2UnpauseResult,
    Aria2ChangeGlobalOptionCall,
    Aria2ChangeGlobalOptionResult,
    Aria2ChangeOptionCall,
    Aria2ChangeOptionResult,
    Aria2GetGlobalOptionCall,
    Aria2GetGlobalOptionResult,
    Aria2GetOptionCall,
    Aria2GetOptionResult,
    Aria2ForceShutdownCall,
    Aria2ForceShutdownResult,
    Aria2GetGlobalStatCall,
    Aria2GetGlobalStatResult,
    Aria2GetSessionInfoCall,
    Aria2GetSessionInfoResult,
    Aria2GetVersionCall,
    Aria2GetVersionResult,
    Aria2SaveSessionCall,
    Aria2SaveSessionResult,
    Aria2ShutdownCall,
    Aria2ShutdownResult,
    Aria2SystemListMethodsCall,
    Aria2SystemListMethodsResult,
    Aria2SystemListNotificationsCall,
    Aria2SystemListNotificationsResult,
    Aria2SystemMulticallCall,
    Aria2SystemMulticallResult,
    Aria2ClientNotificationCall,
    Aria2StringUtf8,
    Aria2ServerOpResult,
    Aria2ClientGidOpParams,
    Aria2ClientGidOpCall,
    Aria2ServerVoidCall,
  }
  export declare type Aria2RpcHost<
    Protocol extends 'ws' | 'wss' | 'http' | 'https',
    Host extends string,
    Port extends number
  > = `${Protocol}://${Host}:${Port}/jsonrpc`
}
